brands_list = [
    "Adidas",
    "Big Lots",
    "Kmart",
    "Ace Hardware",
    "Forever 21",
    "Hot Topic",
    "Menards",
    "Advil",
    "Tide",
    "Bayer",
    "GE",
    "Febreze",
    "Kenmore",
    "Dawn",
    "Amazon",
    "Tylenol",
    "Kohls",
    "Cascade",
    "Arm And Hammer",
    "Downy",
    "Converse",
    "Lowes",
    "Swiffer",
    "Pledge",
    "BJs",
    "Gucci"
]

brands_finished_not_found = [
    "Ashley Furniture",
    "Lysol",
    "Levi's",
    "TJ Maxx",
    "Motrin",
    "American Eagle",
    "Maytag",
    "Sams Club",
    "Aeropostale",
    "Black & Decker",
    "H&M",
    "Old Navy",
    "Gain",
    "Purina",
    "Behr Paint",
    "Walgreens",
    "Hollister",
    "Nike",
    "Oxi Clean",
    "Band Aid",
    "Macys",
    "Under Armour",
    "JC Penney",
    "Ajax",
    "Home Depot",
    "CVS",
    "Walmart",
    "Dick's Sports",
    "Benadryl",
    "SEARS",
    "Windex",
    "Abercrombie & Fitch",
    "Marshalls",
    "Palmolive",
    "Target",
    "Rite Aid",
    "Mr Clean",
    "Ikea",
    "Kitchen Aid",
    "HomeGoods",
    "Foot Locker",
    "GAP",
    "Frigidaire",
    "Victoria's Secret",
    "Barnes & Noble",
    "Pine Sol",
    "Ebay",
    "Costco",
    "Ross",
    "Aleve",
    "Meijer",
    "Nordstrom",
]